spring:
  application:
    name: proposta-refatorada
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_URL}:5432/proposta?createDatabaseIfNotExist=true
    username: keycloak
    password: password
    hikari:
      connection-timeout: 1000
      idle-timeout: 10000
      minimum-idle: 10
      maximun-pool-size: 20
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  database-platform: org.hibernate.dialect.PostgreSQL94Dialect


analiseFinanceiraClient:
  targetUrl: ${URL_ANALISE}

associaPropostaCartaoClient:
  targetUrl: ${URL_CARTAO}

feign:
  client:
    config:
      analiseFinanceiraClient:
        loggerLevel: full
        connectTimeout: 5000
        readTimeout: 5000

scheduler:
  pesquisa-cartao: 5000

server:
  error:
    include-message: always

logging:
  level:
    br:
      com:
        zup:
          proposta:
            cartao: DEBUG