spring:
  application:
    name: proposta-refatorada
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_URL:localhost}:5432/proposta?createDatabaseIfNotExist=true
    username: keycloak
    password: password
    hikari:
      connection-timeout: 1000
      idle-timeout: 10000
      minimum-idle: 10
      maximun-pool-size: 20
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/auth/realms/teste}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:18080/auth/realms/teste/protocol/openid-connect/certs}


analiseFinanceiraClient:
  targetUrl: ${URL_ANALISE:http://localhost:9999/}


associaPropostaCartaoClient:
  targetUrl: ${URL_CARTAO:http://localhost:8888/}


feign:
  hystrix:
    enabled: true
  client:
    config:
      analiseFinanceiraClient:
        loggerLevel: full
        connectTimeout: 5000
        readTimeout: 5000

scheduler:
  pesquisa-cartao: 5000

server:
  error:
    include-message: always

logging:
  level:
    br:
      com:
        zup:
          proposta:
            cartao: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true


# Jaeger - Habilita ou não
opentracing:
  jaeger:
    enabled: ${JAEGER_ENABLED:true}
  # Jaeger - Nome do serviço
    service-name: ${spring.application.name}
  # Jaeger - Endereço para enviar os metadados (trace, span, etc)
    http-sender:
      url: ${JAEGER_ENDPOINT:http://localhost:14268/api/traces}
  # Jaeger - Tipo de amostragem (probabilístico) e sua configuração (1 = 100%)
    probabilistic-sampler:
      sampling-rate: ${JAEGER_SAMPLER:1}
    rate-limiting-sampler:
      max-traces-per-second: ${JAEGER_SAMPLER_PER_SECOND:10}