spring:
  application:
    name: proposta-refatorada
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/proposta?createDatabaseIfNotExist=true
    username: keycloak
    password: password
    hikari:
      connection-timeout: 1000
      idle-timeout: 10000
      minimum-idle: 10
      maximun-pool-size: 20
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  database-platform: org.hibernate.dialect.PostgreSQL94Dialect


